### ISSUE TITLE
Failed to get the Module Base Address - No Offsets

### ISSUE THREAD

**Issue by tcortega** [Perfare/Zygisk-Il2CppDumper#105]
Hello there, experiencing the same issue that happened at #7 

Game: Survivor.io
Package Name: com.dxx.firenow

**Comment by Perfare** [comment]
This problem should not happen in the latest version, if possible you should provide me the log.

**Comment by tcortega** [comment]
> This problem should not happen in the latest version, if possible you should provide me the log.

Unfortunately I don't have my rooted android device anymore, I'll see if I can get a friend to give it a try and will let you know.

**Comment by JMBQ** [comment]
> This problem should not happen in the latest version, if possible you should provide me the log.


uint64_t get_module_base(const char *module_name)

更新这个函数，应该是下面代码引起的。
```
#if defined(__aarch64__)
            if (strstr(flags, "x") == 0) //TODO
                continue;
#endif
```

**Comment by Perfare** [comment]
@JMBQ 现在是使用dladdr获取基址，这个函数只是备用的
