### ISSUE TITLE
是否支持WSA

### ISSUE THREAD

**Issue by FrothierNine346** [Perfare/Zygisk-Il2CppDumper#110]
安装模块后再打开应用会直接闪退，软件：com.hypergryph.arknights
[20221118121336.log](https://github.com/Perfare/Zygisk-Il2CppDumper/files/10042338/20221118121336.log)

**Comment by JMBQ** [comment]
WSA是什么，我这没闪退，成功dump

**Comment by FrothierNine346** [comment]
> WSA是什么，我这没闪退，成功dump

适用于 Android™ 的 Windows 子系统，api版本确实是32。

**Comment by Perfare** [comment]
我没有测试过，从原理上讲是支持的，你可以自己测试

**Comment by Perfare** [comment]
不好意思是我漏看了，看了下log是dobby的问题，最新版本中我已经移除了dobby并不再使用hook获取handle，如果你有需要可以再尝试一下

**Comment by FrothierNine346** [comment]
> 不好意思是我漏看了，看了下log是dobby的问题，最新版本中我已经移除了dobby并不再使用hook获取handle，如果你有需要可以再尝试一下

已更新到项目最新版本，经测试WSA软件可以正常打开但获取不到dump.cs，“/data/data/com.hypergryph.arknights/files”下没有dump.cs文件。
[20230103162539.log](https://github.com/Perfare/Zygisk-Il2CppDumper/files/10338269/20230103162539.log)
实体机测试无异常可以获取到dump.cs。

**Comment by Perfare** [comment]
log看了下，有两种可能性
1. WSA启动游戏太慢。代码默认是延迟5秒后运行，如果启动太慢就会无法获取到handle，可以试着修改这里看看https://github.com/Perfare/Zygisk-Il2CppDumper/blob/93a2cb26e655636e8ae6480aff41126b5c3ab8ba/module/src/main/cpp/hack.cpp#L49
2. 新的方式仍然不支持WSA。这个的话我就无能为力了。。。
