### ISSUE TITLE
Offset Wrong [Free Fire Game]

### ISSUE THREAD

**Issue by Errcr404** [Perfare/Zygisk-Il2CppDumper#114]
I dumped free fire with game guardian and libdumper GUI, and the offsets are correct. But with Zygisk the offsets came differents

**Comment by Perfare** [comment]
You should provide me with more information, such as the game package name and relevant screenshots of the problem you mentioned.

**Comment by ThunderMods** [comment]
maybe because of different arch?

**Comment by Game-Guardian** [comment]
I have same problem offsets different when I use zygisk on mobile legend and blade idle

**Comment by Yorgun66** [comment]
![Screenshot_2023-03-07-22-17-01-963_com topjohnwu magisk](https://user-images.githubusercontent.com/105130201/223529799-2f025076-6260-41d8-8682-3b2de88bbc58.jpg)
 kurulum hatası alıyorum neden acaba
