### ISSUE TITLE
game crashes without dump

### ISSUE THREAD

**Issue by commonuserlol** [Perfare/Zygisk-Il2CppDumper#124]
hello, Genshin Impact crashes without a dump file. there are no errors in logcat, I am attaching a screenshot with the error that frida received (if anything, without the module, the game was launched with frida). thank you in advance.
device info: android 12, magisk v25.2
![screen](https://user-images.githubusercontent.com/111648021/225402977-dd8c637e-8899-4382-93f6-55d7557d744d.png)

**Comment by Perfare** [comment]
The game hides the il2cpp api.
