### ISSUE TITLE
能否解决libil2cpp.so没有导出函数il2cpp_assembly_get_image？

### ISSUE THREAD

**Issue by alienwu2018** [Perfare/Zygisk-Il2CppDumper#125]
某些游戏不清楚是做过处理还是unity版本的问题并没有到处il2cpp_assembly_get_image，因此进行dump的时候由于没有il2cpp_assembly_get_image符号导致无法dump

**Comment by JMBQ** [comment]
> @Perfare
> 其中一个游戏就是com.fct.global
> il2cpp_assembly_get_image 被改名为 il2cpp_dk1::num_xxxxxxxx

直接调用指针 assemblies[i]->image，2020.3.11f1是存在这个指针的

**Comment by Perfare** [comment]
易盾的基本操作罢了，把il2cpp_assembly_get_image符号改了成了`il2cpp_dk1::num_xxxxxxxxx`
@mavisutera 既然都知道il2cpp_assembly_get_image被改成了`il2cpp_dk1::num_xxxxxxxxx`，那为啥不直接`il2cpp_assembly_get_image = dlsym(handle, "il2cpp_dk1::num_xxxxxxxxx")`不就好了
