### ISSUE TITLE
this is a titile

### ISSUE THREAD

**Issue by w296488320** [Perfare/Zygisk-Il2CppDumper#131]
https://github.com/w296488320/XposedJniTrace
我最近改了一些东西，想做一个il2cpp的调用监听。现在采用的是libffi动态生成替换函数，然后在回溯方法里面，打印调用栈和方法信息，这样就知道哪些方法被调用了  。但是总是sign11 。我是基于xposed实现的 。但是存在点问题，感兴趣和我一起完善他么？

**Comment by Perfare** [comment]
你好，感谢你的邀请，不过我暂时没有一起开发这个项目的想法。
另外关于il2cpp的trace这里有个现成的项目你可以看看https://github.com/vfsfitvnm/frida-il2cpp-bridge

**Comment by w296488320** [comment]
> 你好，感谢你的邀请，不过我暂时没有一起开发这个项目的想法。 另外关于il2cpp的trace这里有个现成的项目你可以看看https://github.com/vfsfitvnm/frida-il2cpp-bridge

感谢回复，这个项目我知道，我想通过xposed去注入的方式实现一下，现在检测firda的方式太多了，但是检测lsp却很难 。想着研究一下。再次感谢项目开源 。
