### ISSUE TITLE
Game crash with no dump.cs

### ISSUE THREAD

**Issue by pritamdstan** [Perfare/Zygisk-Il2CppDumper#87]
Using zygisk dumper.
OS: Android 10
![Screenshot_2022-03-01-20-51-00-131_com pluscubed matlog](https://user-images.githubusercontent.com/21976091/156196616-1b35401d-5524-4691-9711-efb16c8da170.jpg)

![IMG_20220303_000749](https://user-images.githubusercontent.com/21976091/156426550-c9024400-ca5c-42e8-b563-d371a8df5a66.jpg)

**Comment by Perfare** [comment]
Tested arm64 and arm version and works fine now.
