### ISSUE TITLE
月圆之夜无dump.cs

### ISSUE THREAD

**Issue by mitiandashuaibi** [Perfare/Zygisk-Il2CppDumper#91]
TapTap上下载的游戏，如果直接使用安装包的il2cpp会提示System.IO.EndOfStreamException: 无法在流的结尾之外进行读取
而使用模块却在data/data/月圆之夜目录的file目录下没用dump.cs生成，使用gg进行内存导出有多个bin，合成失败。。。。。。

**Comment by Agerthanana** [comment]
Aa

**Comment by mitiandashuaibi** [comment]
> 

？

**Comment by Agerthanana** [comment]
Where to get module?

Pada tanggal Sen, 16 Mei 2022 08.07, mitiandashuaibi <
***@***.***> menulis:

**Comment by mitiandashuaibi** [comment]
You can refer to the following content to build a module:
How to use
Install Magisk v24 or later and enable Zygisk
Build module
GitHub Actions
Fork this repo
Go to the Actions tab in your forked repo
In the left sidebar, click the Build workflow.
Above the list of workflow runs, select Run workflow
Input the game package name and click Run workflow
Wait for the action to complete and download the artifact
Android Studio
Download the source code
Edit game.h, modify GamePackageName to the game package name
Use Android Studio to run the gradle task :module:assembleRelease to compile, the zip package will be generated in the out folder
Install module in Magisk
Start the game, dump.cs will be generated in the /data/data/GamePackageName/files/ directory

**Comment by JMBQ** [comment]
这个游戏貌似隐藏了il2cpp的api(全部？)，导致无法dump

**Comment by JMBQ** [comment]
已提供解法：https://github.com/JMBQ/dump-games/blob/main/%E8%BF%9B%E5%87%BB%E7%9A%84%E6%89%8B%E6%B8%B8%EF%BC%9A%E6%9C%88%E5%9C%86%E4%B9%8B%E5%A4%9C.md
