### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by VanHoevenTR** [Perfare/Zygisk-Il2CppDumper#94]
The game Fantasy Life Online crashes as soon as Zygisk-Il2CppDumper trying to dump

My phone running Android 11 with Magisk 25.0

Game link: https://apkcombo.com/apk-downloader/#package=com.boltrend.floen&arches=armeabi-v7a

Log:
[logs.txt](https://github.com/Perfare/Zygisk-Il2CppDumper/files/9079324/logs.txt)

**Comment by Perfare** [comment]
> why is it closed?

fixed.
